accessing
exampleInput
	^ '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title></title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
  <meta name=''ocr-system'' content=''tesseract 4.1.1'' />
  <meta name=''ocr-capabilities'' content=''ocr_page ocr_carea ocr_par ocr_line ocrx_word ocrp_wconf''/>
 </head>
 <body>
  <div class=''ocr_page'' id=''page_1'' title=''image "/tmp/pharo-tempfile/2020-09-29T153428269067-0400.tiff"; bbox 0 0 933 1700; ppageno 0''>
   <div class=''ocr_carea'' id=''block_1_1'' title="bbox 65 156 859 326">
    <p class=''ocr_par'' id=''par_1_1'' lang=''eng'' title="bbox 65 156 859 326">
      ', HocrLine exampleInputTwoWords, '
    </p>
   </div>
  </div>
 </body>
</html>
'