accessing
exampleInput
	^ '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title></title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
  <meta name=''ocr-system'' content=''tesseract 4.1.1'' />
  <meta name=''ocr-capabilities'' content=''ocr_page ocr_carea ocr_par ocr_line ocrx_word ocrp_wconf''/>
 </head>
 <body>
  <div class=''ocr_page'' id=''page_1'' title=''image "/tmp/pharo-tempfile/2020-09-29T153428269067-0400.tiff"; bbox 0 0 933 1700; ppageno 0''>
   <div class=''ocr_carea'' id=''block_1_1'' title="bbox 65 156 859 326">
    <p class=''ocr_par'' id=''par_1_1'' lang=''eng'' title="bbox 65 156 859 326">
     <span class=''ocr_line'' id=''line_1_1'' title="bbox 186 156 739 180; baseline 0.002 -1; x_size 32; x_descenders 8; x_ascenders 8">
      <span class=''ocrx_word'' id=''word_1_1'' title=''bbox 186 156 222 179; x_wconf 0''>A</span>
      <span class=''ocrx_word'' id=''word_1_2'' title=''bbox 226 156 499 180; x_wconf 0''>TRAMART</span>
      <span class=''ocrx_word'' id=''word_1_3'' title=''bbox 544 156 739 180; x_wconf 0''>HYré4T5S</span>
     </span>
     <span class=''ocr_line'' id=''line_1_2'' title="bbox 186 197 739 229; baseline 0.002 -1; x_size 40.666668; x_descenders 10.166667; x_ascenders 10.166667">
      <span class=''ocrx_word'' id=''word_1_4'' title=''bbox 186 197 301 228; x_wconf 73''>46/7</span>
      <span class=''ocrx_word'' id=''word_1_5'' title=''bbox 345 197 539 228; x_wconf 95''>RIVER</span>
      <span class=''ocrx_word'' id=''word_1_6'' title=''bbox 583 198 739 229; x_wconf 96''>ROAD</span>
     </span>
     <span class=''ocr_line'' id=''line_1_3'' title="bbox 65 245 859 278; baseline 0.003 -2; x_size 40.666668; x_descenders 10.166667; x_ascenders 10.166667">
      <span class=''ocrx_word'' id=''word_1_7'' title=''bbox 65 245 459 276; x_wconf 90''>WILLINGTON</span>
      <span class=''ocrx_word'' id=''word_1_8'' title=''bbox 502 246 608 277; x_wconf 88''>CT.</span>
      <span class=''ocrx_word'' id=''word_1_9'' title=''bbox 663 246 859 278; x_wconf 26''>06279</span>
     </span>
     <span class=''ocr_line'' id=''line_1_4'' title="bbox 145 293 778 326; baseline 0.003 -2; x_size 40.666668; x_descenders 10.166667; x_ascenders 10.166667">
      <span class=''ocrx_word'' id=''word_1_10'' title=''bbox 145 293 261 325; x_wconf 69''>WAW</span>
      <span class=''ocrx_word'' id=''word_1_11'' title=''bbox 320 289 333 339; x_wconf 36''>xX</span>
      <span class=''ocrx_word'' id=''word_1_12'' title=''bbox 328 293 618 325; x_wconf 47''>TRAMART</span>
      <span class=''ocrx_word'' id=''word_1_13'' title=''bbox 636 295 778 326; x_wconf 85''>.COM</span>
     </span>
    </p>
   </div>
   <div class=''ocr_carea'' id=''block_1_2'' title="bbox 38 491 672 618">
    <p class=''ocr_par'' id=''par_1_2'' lang=''eng'' title="bbox 38 491 672 618">
     <span class=''ocr_line'' id=''line_1_5'' title="bbox 40 491 672 523; baseline 0.003 -2; x_size 40.688171; x_descenders 10.172043; x_ascenders 10.172043">
      <span class=''ocrx_word'' id=''word_1_14'' title=''bbox 40 491 309 522; x_wconf 1''>1Q09424505-001</span>
      <span class=''ocrx_word'' id=''word_1_15'' title=''bbox 338 492 452 522; x_wconf 96''>SUNOCO</span>
      <span class=''ocrx_word'' id=''word_1_16'' title=''bbox 476 492 672 523; x_wconf 71''>0522461800</span>
     </span>
     <span class=''ocr_line'' id=''line_1_6'' title="bbox 38 538 314 570; baseline 0.004 -1; x_size 40.688171; x_descenders 10.172043; x_ascenders 10.172043">
      <span class=''ocrx_word'' id=''word_1_17'' title=''bbox 38 538 94 569; x_wconf 95''>467</span>
      <span class=''ocrx_word'' id=''word_1_18'' title=''bbox 118 538 215 569; x_wconf 96''>RIVER</span>
      <span class=''ocrx_word'' id=''word_1_19'' title=''bbox 238 538 314 570; x_wconf 96''>ROAD</span>
     </span>
     <span class=''ocr_line'' id=''line_1_7'' title="bbox 38 586 393 618; baseline 0 -1; x_size 40.688171; x_descenders 10.172043; x_ascenders 10.172043">
      <span class=''ocrx_word'' id=''word_1_20'' title=''bbox 38 586 234 618; x_wconf 95''>WILLINGTON</span>
      <span class=''ocrx_word'' id=''word_1_21'' title=''bbox 298 587 334 617; x_wconf 76''>CT</span>
      <span class=''ocrx_word'' id=''word_1_22'' title=''bbox 358 587 393 617; x_wconf 95''>06</span>
     </span>
    </p>
   </div>
   <div class=''ocr_carea'' id=''block_1_3'' title="bbox 38 779 846 1149">
    <p class=''ocr_par'' id=''par_1_3'' lang=''eng'' title="bbox 97 779 832 912">
     <span class=''ocr_line'' id=''line_1_8'' title="bbox 97 779 830 824; baseline 0.003 -10; x_size 36.38298; x_descenders 5.3829789; x_ascenders 8">
      <span class=''ocrx_word'' id=''word_1_23'' title=''bbox 97 779 194 824; x_wconf 89''>Descr.</span>
      <span class=''ocrx_word'' id=''word_1_24'' title=''bbox 536 785 591 820; x_wconf 77''>aty</span>
      <span class=''ocrx_word'' id=''word_1_25'' title=''bbox 715 786 830 816; x_wconf 96''>amount</span>
     </span>
     <span class=''ocr_line'' id=''line_1_9'' title="bbox 97 878 832 912; baseline 0.003 -2; x_size 37.590908; x_descenders 5.5; x_ascenders 8.590909">
      <span class=''ocrx_word'' id=''word_1_26'' title=''bbox 97 878 174 910; x_wconf 92''>VITA</span>
      <span class=''ocrx_word'' id=''word_1_27'' title=''bbox 197 879 214 910; x_wconf 85''>C</span>
      <span class=''ocrx_word'' id=''word_1_28'' title=''bbox 237 879 333 910; x_wconf 85''>COCNT</span>
      <span class=''ocrx_word'' id=''word_1_29'' title=''bbox 357 879 413 911; x_wconf 95''>WIR</span>
      <span class=''ocrx_word'' id=''word_1_30'' title=''bbox 440 880 472 910; x_wconf 95''>16</span>
      <span class=''ocrx_word'' id=''word_1_31'' title=''bbox 581 880 587 911; x_wconf 64''>1</span>
      <span class=''ocrx_word'' id=''word_1_32'' title=''bbox 756 880 832 912; x_wconf 75''>5.00</span>
     </span>
    </p>

    <p class=''ocr_par'' id=''par_1_4'' lang=''eng'' title="bbox 38 927 833 1053">
     <span class=''ocr_line'' id=''line_1_10'' title="bbox 38 927 832 959; baseline 0.004 -3; x_size 37.590908; x_descenders 5.5; x_ascenders 8.590909">
      <span class=''ocrx_word'' id=''word_1_33'' title=''bbox 38 927 53 956; x_wconf 91''>T</span>
      <span class=''ocrx_word'' id=''word_1_34'' title=''bbox 99 927 173 957; x_wconf 92''>LINK</span>
      <span class=''ocrx_word'' id=''word_1_35'' title=''bbox 198 927 273 957; x_wconf 90''>JRKY</span>
      <span class=''ocrx_word'' id=''word_1_36'' title=''bbox 297 927 452 958; x_wconf 92''>PEPPERED</span>
      <span class=''ocrx_word'' id=''word_1_37'' title=''bbox 581 928 588 958; x_wconf 62''>]</span>
      <span class=''ocrx_word'' id=''word_1_38'' title=''bbox 756 929 832 959; x_wconf 75''>6.93</span>
     </span>
     <span class=''ocr_line'' id=''line_1_11'' title="bbox 417 1017 833 1062; baseline 0.002 -10; x_size 36.38298; x_descenders 5.3829789; x_ascenders 8">
      <span class=''ocrx_word'' id=''word_1_39'' title=''bbox 417 1017 567 1062; x_wconf 58''>Subtotal</span>
      <span class=''ocrx_word'' id=''word_1_40'' title=''bbox 742 1023 833 1053; x_wconf 60''>11.99</span>
     </span>
    </p>

    <p class=''ocr_par'' id=''par_1_5'' lang=''eng'' title="bbox 517 1064 832 1110">
     <span class=''ocr_line'' id=''line_1_12'' title="bbox 517 1064 832 1110; baseline 0.006 -10; x_size 37.38298; x_descenders 5.3829789; x_ascenders 9">
      <span class=''ocrx_word'' id=''word_1_41'' title=''bbox 517 1064 573 1110; x_wconf 96''>Tax</span>
      <span class=''ocrx_word'' id=''word_1_42'' title=''bbox 757 1070 832 1102; x_wconf 95''>0.44</span>
     </span>
    </p>

    <p class=''ocr_par'' id=''par_1_6'' lang=''eng'' title="bbox 250 1116 846 1149">
     <span class=''ocr_line'' id=''line_1_13'' title="bbox 250 1116 846 1149; baseline 0.003 -2; x_size 37.590908; x_descenders 5.5; x_ascenders 8.590909">
      <span class=''ocrx_word'' id=''word_1_43'' title=''bbox 250 1116 445 1148; x_wconf 95''>TOTAL</span>
      <span class=''ocrx_word'' id=''word_1_44'' title=''bbox 660 1118 846 1149; x_wconf 0''>12-43</span>
     </span>
    </p>
   </div>
   <div class=''ocr_carea'' id=''block_1_4'' title="bbox 456 1163 833 1248">
    <p class=''ocr_par'' id=''par_1_7'' lang=''eng'' title="bbox 456 1163 833 1248">
     <span class=''ocr_line'' id=''line_1_14'' title="bbox 496 1163 833 1198; baseline 0 -3; x_size 34.85294; x_descenders 4.852941; x_ascenders 9.2647057">
      <span class=''ocrx_word'' id=''word_1_45'' title=''bbox 496 1165 573 1195; x_wconf 71''>CASH</span>
      <span class=''ocrx_word'' id=''word_1_46'' title=''bbox 617 1163 632 1198; x_wconf 71''>$</span>
      <span class=''ocrx_word'' id=''word_1_47'' title=''bbox 736 1166 833 1195; x_wconf 57''>20.09</span>
     </span>
     <span class=''ocr_line'' id=''line_1_15'' title="bbox 456 1210 832 1248; baseline 0.003 -5; x_size 38.38298; x_descenders 5.3829789; x_ascenders 10">
      <span class=''ocrx_word'' id=''word_1_48'' title=''bbox 456 1212 573 1248; x_wconf 87''>Charge</span>
      <span class=''ocrx_word'' id=''word_1_49'' title=''bbox 616 1210 632 1247; x_wconf 64''>$</span>
      <span class=''ocrx_word'' id=''word_1_50'' title=''bbox 736 1213 832 1244; x_wconf 45''>-7.57</span>
     </span>
    </p>
   </div>
   <div class=''ocr_carea'' id=''block_1_5'' title="bbox 37 1308 833 1582">
    <p class=''ocr_par'' id=''par_1_8'' lang=''eng'' title="bbox 37 1308 833 1582">
     <span class=''ocr_line'' id=''line_1_16'' title="bbox 278 1308 632 1341; baseline 0.003 -1; x_size 41.563217; x_descenders 10.390804; x_ascenders 10.390804">
      <span class=''ocrx_word'' id=''word_1_51'' title=''bbox 278 1308 472 1340; x_wconf 95''>THANK</span>
      <span class=''ocrx_word'' id=''word_1_52'' title=''bbox 516 1309 632 1341; x_wconf 96''>YOU</span>
     </span>
     <span class=''ocr_line'' id=''line_1_17'' title="bbox 117 1356 793 1388; baseline 0.003 -2; x_size 41.563217; x_descenders 10.390804; x_ascenders 10.390804">
      <span class=''ocrx_word'' id=''word_1_53'' title=''bbox 117 1356 352 1386; x_wconf 67''>PLEASE</span>
      <span class=''ocrx_word'' id=''word_1_54'' title=''bbox 397 1357 552 1387; x_wconf 96''>COME</span>
      <span class=''ocrx_word'' id=''word_1_55'' title=''bbox 597 1358 793 1388; x_wconf 95''>AGAIN</span>
     </span>
     <span class=''ocr_line'' id=''line_1_18'' title="bbox 241 1403 672 1436; baseline 0.002 -2; x_size 41.563217; x_descenders 10.390804; x_ascenders 10.390804">
      <span class=''ocrx_word'' id=''word_1_56'' title=''bbox 241 1403 393 1434; x_wconf 96''>FREE</span>
      <span class=''ocrx_word'' id=''word_1_57'' title=''bbox 437 1404 672 1436; x_wconf 95''>COFFEE</span>
     </span>
     <span class=''ocr_line'' id=''line_1_19'' title="bbox 197 1451 712 1484; baseline 0.004 -2; x_size 41.563217; x_descenders 10.390804; x_ascenders 10.390804">
      <span class=''ocrx_word'' id=''word_1_58'' title=''bbox 197 1451 274 1482; x_wconf 95''>ON</span>
      <span class=''ocrx_word'' id=''word_1_59'' title=''bbox 317 1451 432 1483; x_wconf 95''>THE</span>
      <span class=''ocrx_word'' id=''word_1_60'' title=''bbox 487 1452 592 1484; x_wconf 26''>ST</span>
      <span class=''ocrx_word'' id=''word_1_61'' title=''bbox 637 1453 712 1484; x_wconf 93''>OF</span>
     </span>
     <span class=''ocr_line'' id=''line_1_20'' title="bbox 37 1499 833 1532; baseline 0.004 -2; x_size 41.563217; x_descenders 10.390804; x_ascenders 10.390804">
      <span class=''ocrx_word'' id=''word_1_62'' title=''bbox 37 1499 93 1530; x_wconf 89''>ST#</span>
      <span class=''ocrx_word'' id=''word_1_63'' title=''bbox 143 1499 233 1530; x_wconf 81''>10060</span>
      <span class=''ocrx_word'' id=''word_1_64'' title=''bbox 257 1499 333 1531; x_wconf 91''>TILL</span>
      <span class=''ocrx_word'' id=''word_1_65'' title=''bbox 357 1499 432 1531; x_wconf 83''>XXXX</span>
      <span class=''ocrx_word'' id=''word_1_66'' title=''bbox 456 1500 513 1531; x_wconf 61''>DR#</span>
      <span class=''ocrx_word'' id=''word_1_67'' title=''bbox 542 1500 548 1531; x_wconf 92''>1</span>
      <span class=''ocrx_word'' id=''word_1_68'' title=''bbox 577 1500 673 1532; x_wconf 86''>TRAN#</span>
      <span class=''ocrx_word'' id=''word_1_69'' title=''bbox 702 1501 833 1532; x_wconf 74''>1022969</span>
     </span>
     <span class=''ocr_line'' id=''line_1_21'' title="bbox 37 1547 833 1582; baseline 0.003 -4; x_size 41.563217; x_descenders 10.390804; x_ascenders 10.390804">
      <span class=''ocrx_word'' id=''word_1_70'' title=''bbox 37 1547 108 1578; x_wconf 89''>CSH:</span>
      <span class=''ocrx_word'' id=''word_1_71'' title=''bbox 137 1547 153 1578; x_wconf 95''>7</span>
      <span class=''ocrx_word'' id=''word_1_72'' title=''bbox 502 1547 652 1582; x_wconf 84''>12/26/15</span>
      <span class=''ocrx_word'' id=''word_1_73'' title=''bbox 681 1549 833 1580; x_wconf 90''>14:37:49</span>
     </span>
    </p>
   </div>
  </div>
 </body>
</html>
'